# Generated by Django 5.0.3 on 2024-04-02 05:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_image', models.CharField(max_length=255)),
                ('xona_soni', models.IntegerField()),
                ('manzil', models.CharField(max_length=255)),
                ('narx', models.IntegerField()),
                ('body', models.CharField(max_length=255)),
                ('yashash_maydoni', models.IntegerField()),
                ('remont', models.CharField(choices=[('Qoniqarli', 'Qoniqarli'), ('Yaxshi', 'Yaxshi'), ('Yevro', 'Yevro')], max_length=255, verbose_name='remont status')),
                ('etaj', models.IntegerField()),
                ('kun', models.DateField()),
                ('vaqt', models.TimeField()),
                ('Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
